name: Build wheels

# Source: https://raw.githubusercontent.com/pypa/cibuildwheel/main/examples/github-deploy.yml

env:
  CIBW_SKIP: "cp36-*"

# Build on every branch push, tag push, and pull request change:
on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22.0

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
